// Gorilla_Caps/src/app/gestion/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { local } from 'd3-selection';
import { AuthService } from 'src/app/auth.service';
import { GorillaApiService } from 'src/app/gorilla-api.service';
import { MenuComponent } from 'src/app/menu/menu.component';
import Swal, { SweetAlertIcon } from 'sweetalert2';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;


  constructor(private formBuilder: FormBuilder,
              public user:GorillaApiService,
              private router:Router,
              private aService: AuthService,
              private menu: MenuComponent) { }

  ngOnInit(): void {
    this.loginForm = this.formBuilder.group({
      email: ['', Validators.required],
      password: ['', Validators.required]
    });
  }

  login(): void {
    this.user.findBy_UsernamePassword(this.loginForm.value.email, this.loginForm.value.password).subscribe(
      (response: any) => {
        if(response.user){
        this.aService.setToken(response.token);
        this.aService.setID(response.user.id);
        localStorage.setItem('admin', response.user.admin);
        localStorage.setItem('empleado', response.user.empleado);
        
        this.router.navigate(['/Catalogo']);
        
        setTimeout(() => {
          this.menu.reloadData();
        }, 2000);
        this.mostrarSweetAlert('Bienvenido', '', 'success');
        }else{
          this.mostrarSweetAlert('Error', 'Usuario o contraseña incorrectos', 'error');
        }

      },
      (error: any) => {
        // Manejo de errores en caso de que la solicitud falle.
        this.mostrarSweetAlert('Error', 'Usuario o contraseña incorrectos', 'error');
        console.error(error);
      }
    );
  }


  mostrarSweetAlert(title: string, text: string, icon: SweetAlertIcon): void {
    Swal.fire({
      title,
      text,
      html: '<i class="fas fa-spinner fa-spin"></i> Iniciando sesión...',
      icon,
      showConfirmButton: false,
    });
  }
}

<!-- login.component.html -->
<h1 class="title" style="text-align: center;">GorillaCaps</h1>
<form class="login-form" [formGroup]="loginForm">
  <mat-form-field appearance="fill">
    <mat-label>Email</mat-label>
    <input matInput formControlName="email" placeholder="Ingrese su email">
  </mat-form-field>

  <mat-form-field appearance="fill">
    <mat-label>Contraseña</mat-label>
    <input matInput formControlName="password" type="password" placeholder="Ingrese su contraseña">
  </mat-form-field>

  <button mat-raised-button color="primary" (click)="login()">Iniciar sesión</button>

  <div class="register-link">
    ¿No tienes una cuenta? <a href="/Registro">Regístrate aquí</a>
  </div>
</form>

// PWA-Gorilla_Caps/src/pages/Login.jsx
// eslint-disable-next-line no-unused-vars
import React, { useState } from "react";
import Swal from "sweetalert2";
import "bootstrap/dist/css/bootstrap.min.css"; // Asegúrate de importar el CSS de Bootstrap
import "./Login.css"; // Asegúrate de importar el archivo CSS

// eslint-disable-next-line react/prop-types
const Login = ({ setAuthenticated }) => {
  const [formData, setFormData] = useState({
    email: "",
    password: "",
  });

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleLogin = async () => {
    try {
      const response = await fetch("/api/Login/authenticate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include", // Habilitar credenciales
        body: JSON.stringify(formData), // Convertir a JSON y enviar en el cuerpo
      });

      if (!response.ok) {
        throw new Error(`Error: ${response.status} - ${response.statusText}`);
      }

      const data = await response.json();

      if (data.user) {
        localStorage.setItem("token", data.token);
        localStorage.setItem("id", data.user.id);
        localStorage.setItem("admin", data.user.admin);
        localStorage.setItem("empleado", data.user.empleado);
        // Actualiza el estado de autenticación a true
        setAuthenticated(true);

        // Muestra una alerta de éxito
        Swal.fire({
          icon: "success",
          title: "Inicio de sesión exitoso",
          text: "Redirigiendo a la página de catálogo...",
          showConfirmButton: false,
          timer: 1500,
        });

        // Redirige al usuario después de un inicio de sesión exitoso
        setTimeout(() => {
          window.location.href = "/Catalogo";
        }, 1500);
      } else {
        // Muestra una alerta de error
        Swal.fire({
          icon: "error",
          title: "Error",
          text: "Usuario o contraseña incorrectos",
        });
      }
    } catch (error) {
      // Muestra una alerta de error
      Swal.fire({
        icon: "error",
        title: "Error",
        text: `Error al realizar la solicitud: ${error.message}`,
      });
    }
  };

  return (
    <div className="container my-5 text-center">
      <div className="row justify-content-center">
        <div className="col-md-6">
          <div className="card login-form">
            <div className="card-body">
              <img
                src="../../public/logoD.jpg"
                alt="GorillaCaps"
                className="imagen-cabecera"
              />
              <br />
              <div className="form-group">
                <label>Email</label>
                <input
                  type="text"
                  name="email"
                  value={formData.email}
                  onChange={handleInputChange}
                  className="form-control"
                  placeholder="Ingrese su email"
                />
              </div>

              <div className="form-group">
                <label>Contraseña</label>
                <input
                  type="password"
                  name="password"
                  value={formData.password}
                  onChange={handleInputChange}
                  className="form-control"
                  placeholder="Ingrese su contraseña"
                />
              </div>

              <button
                className="btn btn-primary btn-block"
                onClick={handleLogin}
              >
                Iniciar sesión
              </button>

              <div className="register-link">
                ¿No tienes una cuenta?{" "}
                <a href="/register" className="link-primary">
                  Regístrate aquí
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
