// Gorilla_Caps/src/app/gestion/cliente/ventas-c/ventas-c.component.ts
import { Component, OnInit } from '@angular/core';
import { GorillaApiService } from 'src/app/gorilla-api.service';

@Component({
  selector: 'app-ventas-c',
  templateUrl: './ventas-c.component.html',
  styleUrls: ['./ventas-c.component.css']
})
export class VentasCComponent implements OnInit {
  ventasPorAprobar: any[] = [];
  ventasAprobadas: any[] = [];
  mostrarPendientes: boolean = true;
  mostrarEnCamino: boolean = false;
  idUsuario: number = 0;
    // Función para obtener las claves de un objeto
    getObjectKeys(obj: any): string[] {
      return obj ? Object.keys(obj) : [];
    }

  constructor(private ventasService: GorillaApiService) { }

  ngOnInit(): void {
    this.idUsuario = Number(localStorage.getItem('id'));
    console.log(this.idUsuario);
    this.getCompras();
  }

  getCompras() {
    this.ventasService.getMisCompras(this.idUsuario).subscribe(
      (response: any) => {
        console.log(response);
        console.log(response.ventasPA);
        console.log(response.ventasA);
        if (response) {
          this.ventasPorAprobar = response.ventasPA || [];
          this.ventasAprobadas = response.ventasA || [];
          console.log(this.ventasPorAprobar);
          console.log(this.ventasAprobadas);
        } else {
          this.ventasPorAprobar = [];
          this.ventasAprobadas = [];
        }
      },
      error => console.log(error)
    );
  }

  cambiarVista(vista: string) {
    if (vista === 'pendientes') {
      this.mostrarPendientes = true;
      this.mostrarEnCamino = false;
    } else {
      this.mostrarPendientes = false;
      this.mostrarEnCamino = true;
    }
  }


  getImageUrl(base64Image: string): string {
    if (base64Image) {
      return 'data:image/jpeg;base64,' + base64Image;
    }
    // Puedes establecer una imagen de relleno en caso de que no haya imagen
    return './assets/default.jpg';
  }
}

<div class="container my-3">
  <div class="row">
    <div class="col-12 mb-4 text-center">
      <div class="card border-primary">
        <div class="card-body">
          <h5 class="card-title"><i class="fas fa-truck"></i> Compras en camino</h5>
          <p class="card-text">Revisa el estado de tus compras que ya están en camino</p>
          <button id="btn-en-camino" class="btn btn-primary" (click)="cambiarVista('enCamino')"
            [class.active]="mostrarEnCamino">Ver compras en camino</button>
        </div>
      </div>

      <div class="card border-primary">
        <div class="card-body">
          <h5 class="card-title"><i class="fas fa-shopping-bag"></i> Compras pendientes</h5>
          <p class="card-text">Revisa tus compras pendientes de envío</p>
          <button id="btn-pendientes" class="btn btn-primary" (click)="cambiarVista('pendientes')"
            [class.active]="mostrarPendientes">Ver compras pendientes</button>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container my-3">
  <div class="row">
    <!-- Ventas pendientes -->
    <div class="col-md-6" *ngIf="mostrarPendientes">
      <div class="card mb-5">
        <div class="card-header bg-primary text-white">
          <h2 class="mb-0">Pendientes de Envío</h2>
        </div>
        <div class="card-body">
          <ng-container *ngIf="ventasPorAprobar.length > 0; else noVentasPendientes">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Fecha</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Talla</th>
                    <th scope="col">Imagen</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio unitario</th>
                    <th scope="col">Total</th>
                  </tr>
                </thead>
                <tbody>
                  <ng-container *ngFor="let venta of ventasPorAprobar">
                    <ng-container *ngFor="let fecha of getObjectKeys(venta.productos)">
                      <ng-container *ngFor="let productoKey of getObjectKeys(venta.productos[fecha])">
                        <tr>
                          <td>{{ venta.fecha }}</td>
                          <td>{{ productoKey }}</td>
                          <td>{{ venta.productos[fecha][productoKey].talla }}</td>
                          <td>
                            <img [src]="venta.productos[fecha][productoKey].imagen" alt=""
                              style="width: 50px; height: 50px;" />
                          </td>
                          <td>{{ venta.productos[fecha][productoKey].cantidad }}</td>
                          <td>${{ venta.productos[fecha][productoKey].precio }}</td>
                          <td>
                            ${{ venta.productos[fecha][productoKey].cantidad *
                            venta.productos[fecha][productoKey].precio }}
                          </td>
                        </tr>
                      </ng-container>
                    </ng-container>
                  </ng-container>
                </tbody>
              </table>
            </div>
          </ng-container>
          <ng-template #noVentasPendientes>
            <p class="text-center">No hay compras pendientes por aprobar.</p>
          </ng-template>
        </div>
      </div>
    </div>



    <!-- Ventas en camino -->
    <div class="col-md-6" *ngIf="mostrarEnCamino">
      <div class="card mb-5">
        <div class="card-header bg-primary text-white">
          <h2 class="mb-0">En Camino</h2>
        </div>
        <div class="card-body">
          <ng-container *ngIf="ventasAprobadas.length > 0; else noVentasEnCamino">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Fecha</th>
                    <th scope="col">Producto</th>
                    <th scope="col">Talla</th>
                    <th scope="col">Imagen</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio unitario</th>
                    <th scope="col">Total</th>
                  </tr>
                </thead>
                <tbody>
                  <ng-container *ngFor="let venta of ventasAprobadas">
                    <ng-container *ngFor="let fecha of getObjectKeys(venta.productos)">
                      <ng-container *ngFor="let productoKey of getObjectKeys(venta.productos[fecha])">
                        <tr>
                          <td>{{ venta.fecha }}</td>
                          <td>{{ productoKey }}</td>
                          <td>{{ venta.productos[fecha][productoKey].talla }}</td>
                          <td>
                            <img [src]="venta.productos[fecha][productoKey].imagen" alt=""
                              style="width: 50px; height: 50px;" />
                          </td>
                          <td>{{ venta.productos[fecha][productoKey].cantidad }}</td>
                          <td>${{ venta.productos[fecha][productoKey].precio }}</td>
                          <td>
                            ${{ venta.productos[fecha][productoKey].cantidad *
                            venta.productos[fecha][productoKey].precio }}
                          </td>
                        </tr>
                      </ng-container>
                    </ng-container>
                  </ng-container>
                </tbody>
              </table>
            </div>
          </ng-container>
          <ng-template #noVentasEnCamino>
            <p class="text-center">Aún no ha realizado una compra o aún no ha sido aprobada.</p>
          </ng-template>
        </div>
      </div>
    </div>
  </div>
</div>

// PWA-Gorilla_Caps/src/pages/VentasC.jsx
import { useState, useEffect } from "react";
import Swal from "sweetalert2";
import "./VentasC.css"; // Asegúrate de importar el archivo CSS

const VentasC = () => {
  const [ventasPorAprobar, setVentasPorAprobar] = useState([]);
  const [ventasAprobadas, setVentasAprobadas] = useState([]);
  const [mostrarPendientes, setMostrarPendientes] = useState(true);
  const [mostrarEnCamino, setMostrarEnCamino] = useState(false);
  const idUsuario = Number(localStorage.getItem("id"));

  useEffect(() => {
    getCompras();
  }, []);

  const getCompras = async () => {
    try {
      const response = await fetch(`/api/VentasC/MisCompras/${idUsuario}`);
      if (!response.ok) {
        throw new Error(
          `Error: ${response.status} - ${response.statusText}`
        );
      }
      const data = await response.json();
      if (data) {
        setVentasPorAprobar(data.ventasPA || []);
        setVentasAprobadas(data.ventasA || []);
      } else {
        setVentasPorAprobar([]);
        setVentasAprobadas([]);
      }
    } catch (error) {
      console.error(`Error al obtener las compras: ${error.message}`);
    }
  };

  const cambiarVista = (vista) => {
    if (vista === "pendientes") {
      setMostrarPendientes(true);
      setMostrarEnCamino(false);
    } else {
      setMostrarPendientes(false);
      setMostrarEnCamino(true);
    }
  };

  const getImageUrl = (base64Image) => {
    if (base64Image) {
      return `data:image/jpeg;base64,${base64Image}`;
    }
    return "./assets/default.jpg";
  };

  return (
    <div className="container my-3">
      <div className="row">
        <div className="col-12 mb-4 text-center">
          {/* Botones de selección */}
          <div className="card border-primary">
            <div className="card-body">
              <h5 className="card-titulo">
                <i className="fas fa-truck"></i> Compras en camino
              </h5>
              <p className="card-text">Revisa el estado de tus compras en camino</p>
              <button
                className={`btn btn-primary ${
                  mostrarEnCamino ? "active" : ""
                }`}
                onClick={() => cambiarVista("enCamino")}
              >
                Ver compras en camino
              </button>
            </div>
          </div>
          <br />
          <br />
          <div className="card border-primary">
            <div className="card-body">
              <h5 className="card-titulo">
                <i className="fas fa-shopping-bag"></i> Compras pendientes
              </h5>
              <p className="card-text">
                Revisa tus compras pendientes de envío
              </p>
              <button
                className={`btn btn-primary ${
                  mostrarPendientes ? "active" : ""
                }`}
                onClick={() => cambiarVista("pendientes")}
              >
                Ver compras pendientes
              </button>
            </div>
          </div>
          {/* Contenido de compras */}
          <div className="container my-12">
            <div className="row">
              <div className="col-md-11">
                {/* Ventas pendientes */}
                {mostrarPendientes && (
                  <div className="card mb-11">
                    <div className="card-header bg-primary text-white">
                      <h2 className="mb-0">Pendientes de Envío</h2>
                    </div>
                    <div>
                      {ventasPorAprobar.length > 0 ? (
                        <div className="table-responsive">
                          <table className="table table-striped">
                            {/* Estructura de la tabla */}
                            <thead>
                              <tr className="header-row">
                                <th scope="col">Fecha</th>
                                <th scope="col">Producto</th>
                                <th scope="col">Imagen</th>
                                <th scope="col">Cantidad</th>
                                <th scope="col">Precio unitario</th>
                                <th scope="col">Total</th>
                              </tr>
                            </thead>
                            <tbody>
                              {/* Mapeo de las ventas */}
                              {ventasPorAprobar.map((venta) => (
                                Object.keys(venta.productos).map((fecha) =>
                                  Object.keys(venta.productos[fecha]).map(
                                    (productoKey) => (
                                      <tr key={productoKey}>
                                        <td>{venta.fecha}</td>
                                        <td>{productoKey}</td>
                                        <td>
                                          <img
                                            src={getImageUrl(
                                              venta.productos[fecha][
                                                productoKey
                                              ].imagen
                                            )}
                                            alt=""
                                            style={{
                                              width: "50px",
                                              height: "50px",
                                            }}
                                          />
                                        </td>
                                        <td>
                                          {venta.productos[fecha][productoKey]
                                            .cantidad}
                                        </td>
                                        <td>
                                          ${
                                            venta.productos[fecha][productoKey]
                                              .precio
                                          }
                                        </td>
                                        <td>
                                          ${
                                            venta.productos[fecha][productoKey]
                                              .cantidad *
                                            venta.productos[fecha][productoKey]
                                              .precio
                                          }
                                        </td>
                                      </tr>
                                    )
                                  )
                                )
                              ))}
                            </tbody>
                          </table>
                        </div>
                      ) : (
                        <p className="text-center">
                          No hay compras pendientes por aprobar.
                        </p>
                      )}
                    </div>
                  </div>
                )}
                {/* Ventas en camino */}
                {mostrarEnCamino && (
                  <div className="card mb-11">
                    <div className="card-header bg-primary text-white">
                      <h2 className="mb-0">En Camino</h2>
                    </div>
                    <div>
                      {ventasAprobadas.length > 0 ? (
                        <div className="table-responsive">
                          <table className="table table-striped">
                            {/* Estructura de la tabla */}
                            <thead>
                              <tr className="header-row">
                                <th scope="col">Fecha</th>
                                <th scope="col">Producto</th>
                                <th scope="col">Imagen</th>
                                <th scope="col">Cantidad</th>
                                <th scope="col">Precio unitario</th>
                                <th scope="col">Total</th>
                              </tr>
                            </thead>
                            <tbody>
                              {/* Mapeo de las ventas */}
                              {ventasAprobadas.map((venta) => (
                                Object.keys(venta.productos).map((fecha) =>
                                  Object.keys(venta.productos[fecha]).map(
                                    (productoKey) => (
                                      <tr key={productoKey}>
                                        <td>{venta.fecha}</td>
                                        <td>{productoKey}</td>
                                        <td>
                                          <img
                                            src={getImageUrl(
                                              venta.productos[fecha][
                                                productoKey
                                              ].imagen
                                            )}
                                            alt=""
                                            style={{
                                              width: "50px",
                                              height: "50px",
                                            }}
                                          />
                                        </td>
                                        <td>
                                          {venta.productos[fecha][productoKey]
                                            .cantidad}
                                        </td>
                                        <td>
                                          ${
                                            venta.productos[fecha][productoKey]
                                              .precio
                                          }
                                        </td>
                                        <td>
                                          ${
                                            venta.productos[fecha][productoKey]
                                              .cantidad *
                                            venta.productos[fecha][productoKey]
                                              .precio
                                          }
                                        </td>
                                      </tr>
                                    )
                                  )
                                )
                              ))}
                            </tbody>
                          </table>
                        </div>
                      ) : (
                        <p className="text-center">
                          Aún no ha realizado una compra o aún no ha sido
                          aprobada.
                        </p>
                      )}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default VentasC;
