// PWA-Gorilla_Caps/src/pages/pagar/Pagar.jsx
// eslint-disable-next-line no-unused-vars
import React, { useEffect, useState } from "react";
import "./Pagar.css";

const Pagar = () => {
  const cardHeaderStyle = {
    fontFamily: "'Times New Roman', Times, serif",
  };
  const [detProductos, setDetProductos] = useState([]);
  const [, setPedidos] = useState([]);
  const [total, setTotal] = useState(0);

  useEffect(() => {
    const idUsuario = Number(localStorage.getItem("id"));
    //const carrito = localStorage.getItem("carrito");
    getPagarTodo(idUsuario);
  }, []);

  const getPagarTodo = async (idUsuario) => {
    try {
      const response = await fetch(`/api/Pedidos/PagarTodo/${idUsuario}`, {
        method: "GET",
        headers: { "Content-Type": "application/json" },
      });
      if (!response.ok) {
        throw new Error("Network response was not ok");
      }

      const data = await response.json();
      console.log(data);
      setDetProductos(data.detProductos);
      setPedidos(data.pedidos);
      setTotal(data.total);
    } catch (error) {
      // Manejar errores
      console.error(error);
    }
  };

  const fromB64 = (b64) => {
    return "data:image/jpeg;base64," + b64;
  };

  return (
    <div className="card">
      <div>
        <h1 className="card-header" style={cardHeaderStyle}>
          Confirmación de pago
        </h1>
      </div>
      <div className="row">
        <div className="col-md-8">
          {detProductos.map((producto, index) => (
            <div className="card mb-3" key={index}>
              <div className="row no-gutters">
                <div className="col-md-4">
                  <img
                    // @ts-ignore
                    src={fromB64(producto.imagen)}
                    className="card-img"
                    alt=""
                    style={{ height: "150px", width: "150px" }}
                  />
                </div>
                <div className="col-md-8">
                  <div className="card-body">
                    <h5 className="card-title">
                      {
                        // @ts-ignore
                        producto.nombre
                      }
                    </h5>
                    <p className="card-text">
                      Modelo:{" "}
                      {
                        // @ts-ignore
                        producto.modelo
                      }
                    </p>
                    <p className="card-text">
                      Descripción:{" "}
                      {
                        // @ts-ignore
                        producto.descripcion
                      }
                    </p>
                    <p className="card-text">
                      Precio:{" "}
                      {
                        // @ts-ignore
                        producto.precio
                      }{" "}
                      | Cantidad:{" "}
                      {
                        // @ts-ignore
                        producto.cantidad
                      }
                    </p>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
        <div className="col-md-4">
          <div className="card">
            <div className="card-body">
              <br />
              <h5 className="card-title">Resumen de Pago</h5>
              <p className="card-text">El total es ${total}</p>

              <form>
                <div className="form-group">
                  <label className="card-text" htmlFor="metodo_pago">
                    Seleccione método de pago:
                  </label>
                  <br />
                  <select
                    className="form-control"
                    id="metodo_pago"
                    name="metodo_pago"
                  >
                    <option value="efectivo">Efectivo</option>
                    <option value="tarjeta">Tarjeta</option>
                  </select>
                </div>
                <div className="form-group">
                  <input type="hidden" name="id" value="" />
                  <br />
                  <br />
                  <br />
                  <button color="accent">Continuar</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Pagar;

// Gorilla_Caps/src/app/gestion/cliente/pedidos/pagar/pagar.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { GorillaApiService } from 'src/app/gorilla-api.service';

@Component({
  selector: 'app-pagar',
  templateUrl: './pagar.component.html',
  styleUrls: ['./pagar.component.css']
})
export class PagarComponent {
  detallePedido: any;
  total: number = 0;
  idPedido: number = -1;



  constructor(private pagar: GorillaApiService, private route: ActivatedRoute) { }

  ngOnInit() {
    this.detallePagar(this.idPedido);
  }


  detallePagar(id: number) {
    this.pagar.pagar(id).subscribe(
      (response: any) => {
        console.log(response);
        this.detallePedido = response.detallesProductos;
        this.total = response.total;
      },
      (error: any) => {
        console.error('Error al obtener los detalles del pedido', error);
      });
  }




}

<!-- <div *ngIf="detallePedido && detallePedido.length > 0"> -->
<h1 class="text-center">Confirmación de Pago</h1>

<div class="row">
  <div class="col-md-8">
    <div *ngFor="let producto of detallePedido" class="card mb-3">

      <div class="row no-gutters">
        <div class="col-md-4">
          <img src="" class="card-img" alt=""
            style="height: 150px; width: 150px;">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">{{ producto.nombre }}</h5>
            <p class="card-text"><small class="text-muted">Modelo: {{ producto.modelo }}</small></p>
            <p class="card-text"><small class="text-muted">Descripción: {{ producto.descripcion }}</small>
            </p>
            <p class="card-text">Precio: ${{ producto.precio }} | Cantidad: {{ producto.cantidad }}</p>
          </div>
        </div>
      </div>

    </div>
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Resumen de Pago</h5>
          <p class="card-text">El total es ${{ total }}</p>
          <form>
            <div class="form-group">
              <label for="metodo_pago">Seleccione método de pago:</label>
              <select class="form-control" id="metodo_pago" name="metodo_pago">
                <option value="efectivo">Efectivo</option>
                <option value="tarjeta">Tarjeta</option>
              </select>
            </div>
            <br>
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block">Continuar</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- </div> -->
  <br><br>
